"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACC_T_Tea = 11;
exports.ACC_T_Stu = 12;
exports.ACC_T_Admin = 13;
exports.MALE = 21;
exports.FEMALE = 22;
exports.SELECT = 31;
exports.QA = 32;
exports.ForT_Comment = 41;
exports.ForT_Question = 42;
exports.ForT_Course = 43;
exports.ForT_Ans = 44;
exports.ForT_Video = 45;
exports.FT_FILE = 52;
exports.FT_IMAGE = 53;
exports.new_comment_course = 98;
exports.new_comment_course_by_teacher = 97;
exports.new_question = 96;
exports.new_comment_question = 95;
exports.new_comment_question_by_teacher = 94;
exports.new_message = 50;
exports.bulletin = 99;
